name: dart_flutter_example
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
    sdk: ">=2.15.1 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    #ui
    #animated_floatactionbuttons: ^0.1.0
    #flutter_swiper: ^1.1.6
    #cupertino_icons: ^0.1.3

    #database
    optional: ^6.1.0+1
    #path_provider: ^1.6.11
    #sqflite: ^1.1.6+3

    #http
    dio: ^4.0.4

    #depency injections
    #get: ^4.1.3

    #log
    #log4d: ^1.0.4

    #reactive
    rxdart: ^0.27.3
    #dwds: ^7.1.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^1.0.0

module:
    androidX: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/astronauta.jpg
        - assets/image1.jpg
        - assets/image2.jpg
        - assets/image3.jpg
        - assets/image4.jpg
        - assets/image5.jpg
        - assets/image6.jpg
        - assets/image7.jpg
        - assets/images.jpeg

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
