name: prueba_flutter
description: A new Flutter project.
version: 1.0.0+1

environment:
    sdk: ">=2.1.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    #ui
    animated_floatactionbuttons: ^0.1.0
    flutter_swiper: ^1.1.6
    cupertino_icons: ^0.1.2
    #database
    optional: ^3.0.2+1
    path_provider: ^1.2.0
    #sqflite: ^1.1.6+3
    #http
    dio: ^2.1.13
    dio_flutter_transformer: ^2.0.10
    jaguar_serializer: ^2.2.12
    #depency injections
    flutter_modular: ^1.2.5+1
    #log
    log4d: ^1.0.4
    #reactive
    rxdart: ^0.22.6

dev_dependencies:
    flutter_test:
        sdk: flutter
    jaguar_serializer_cli: ^2.1.14

module:
    androidX: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

    # The following line ensures that the Material Icons font is
    # included with your application, so that you can use the icons in
    # the material Icons class.
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/astronauta.jpg
        - assets/image1.jpg
        - assets/image2.jpg
        - assets/image3.jpg
        - assets/image4.jpg
        - assets/image5.jpg
        - assets/image6.jpg
        - assets/image7.jpg
        - assets/images.jpeg

    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    #   - family: Schyler
    #     fonts:
    #       - asset: fonts/Schyler-Regular.ttf
    #       - asset: fonts/Schyler-Italic.ttf
    #         style: italic
    #   - family: Trajan Pro
    #     fonts:
    #       - asset: fonts/TrajanPro.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
