# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter Continuous Delivery

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Clone source code
        uses: actions/checkout@v2

      - name: Get java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Get flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          channel: 'stable'

      - name: Show flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze --fatal-infos

      - name: Run tests
        run: flutter test

      - name: Build project
        run: flutter build apk

  build-ios:
    runs-on: macos-latest

    steps:
      - name: Clone source code
        uses: actions/checkout@v2

      - name: Get flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          channel: 'stable'

      - name: Show flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze --fatal-infos

      - name: Run tests
        run: flutter test

      - name: Build project
        run: flutter build ios --release --no-codesign
